In [1]:
import pandas as pd

# Load a tabular dataset

In [2]:
df = pd.read_csv('people-example.csv')

# Pandas basics

In [3]:
df

First Name Last Name        Country  age
0        Bob     Smith  United States   24
1      Alice  Williams         Canada   23
2    Malcolm      Jone        England   22
3      Felix     Brown            USA   23
4       Alex    Cooper         Poland   23
5        Tod  Campbell  United States   22
6      Derek      Ward    Switzerland   25

In [4]:
df.head()

First Name Last Name        Country  age
0        Bob     Smith  United States   24
1      Alice  Williams         Canada   23
2    Malcolm      Jone        England   22
3      Felix     Brown            USA   23
4       Alex    Cooper         Poland   23

In [5]:
df.tail()

First Name Last Name        Country  age
2    Malcolm      Jone        England   22
3      Felix     Brown            USA   23
4       Alex    Cooper         Poland   23
5        Tod  Campbell  United States   22
6      Derek      Ward    Switzerland   25

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 4 columns):
First Name    7 non-null object
Last Name     7 non-null object
Country       7 non-null object
age           7 non-null int64
dtypes: int64(1), object(3)
memory usage: 296.0+ bytes


In [7]:
df.describe()

age
count   7.000000
mean   23.142857
std     1.069045
min    22.000000
25%    22.500000
50%    23.000000
75%    23.500000
max    25.000000

In [10]:
df["Country"].describe()

count                 7
unique                6
top       United States
freq                  2
Name: Country, dtype: object

# Inspect columns of dataset

In [12]:
df['Country']

0    United States
1           Canada
2          England
3              USA
4           Poland
5    United States
6      Switzerland
Name: Country, dtype: object

In [13]:
df['age']

0    24
1    23
2    22
3    23
4    23
5    22
6    25
Name: age, dtype: int64

In [14]:
df['age'].mean()

23.142857142857142

In [15]:
df['age'].max()

25

# Create new columns in our DataFrame

In [16]:
df['Full Name'] = df['First Name'] + ' ' + df['Last Name']

In [17]:
df

First Name Last Name        Country  age       Full Name
0        Bob     Smith  United States   24       Bob Smith
1      Alice  Williams         Canada   23  Alice Williams
2    Malcolm      Jone        England   22    Malcolm Jone
3      Felix     Brown            USA   23     Felix Brown
4       Alex    Cooper         Poland   23     Alex Cooper
5        Tod  Campbell  United States   22    Tod Campbell
6      Derek      Ward    Switzerland   25      Derek Ward

In [18]:
df['age'] * df['age']

0    576
1    529
2    484
3    529
4    529
5    484
6    625
Name: age, dtype: int64

# Use the apply function to do advance transformation of our data

In [19]:
def transform_country(country):
    if country == 'USA':
        return 'United States'
    else:
        return country

In [20]:
transform_country('Brazil')

'Brazil'

In [21]:
transform_country('USA')

'United States'

In [22]:
df['Country'].apply(transform_country)

0    United States
1           Canada
2          England
3    United States
4           Poland
5    United States
6      Switzerland
Name: Country, dtype: object

In [23]:
df['Country'] = df['Country'].apply(transform_country)

In [24]:
df

First Name Last Name        Country  age       Full Name
0        Bob     Smith  United States   24       Bob Smith
1      Alice  Williams         Canada   23  Alice Williams
2    Malcolm      Jone        England   22    Malcolm Jone
3      Felix     Brown  United States   23     Felix Brown
4       Alex    Cooper         Poland   23     Alex Cooper
5        Tod  Campbell  United States   22    Tod Campbell
6      Derek      Ward    Switzerland   25      Derek Ward

# Working with numpy

In [25]:
import numpy as np

In [26]:
a = np.arange(15).reshape(3, 5)

In [27]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [28]:
a.shape

(3, 5)

In [29]:
a.ndim

2

In [30]:
a.dtype

dtype('int64')

# Basic operations

In [31]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )

In [32]:
a

array([20, 30, 40, 50])

In [33]:
b

array([0, 1, 2, 3])

In [34]:
c = a - b

In [35]:
c

array([20, 29, 38, 47])

In [36]:
b**2

array([0, 1, 4, 9])

In [37]:
10*np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [38]:
a<35

array([ True,  True, False, False], dtype=bool)